apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name | default "pingcap-clinic" }}
  labels:
    app: pingcap-clinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingcap-clinic
  template:
    metadata:
      labels:
        app: pingcap-clinic
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Values.diag.serviceAccount | default "pingcap-clinic" }}
      serviceAccountName: {{ .Values.diag.serviceAccount | default "pingcap-clinic" }}
      containers:
      - name: collector
        image: {{ .Values.image.diagImage }}:{{ .Values.image.imageTag | default "latest" }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy | default "IfNotPresent" }}
        {{- if .Values.diag.resources }}
        resources:
{{ toYaml .Values.diag.resources | indent 10 }}
        {{- end }}
        command:
        - /usr/local/bin/diag
        volumeMounts:
        - mountPath: "/var/lib/clinic-cert"
          name: pingcap-clinic-cert
          readOnly: true
        {{- if .Values.diag.volume }}
        - mountPath: "/diag"
          name: "diag-storage"
        {{- end }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CLINIC_TOKEN
          value: {{ required "Please set your Token. You can get your token after signing in to Clinic Server 'https://clinic.pingcap.com.cn'" .Values.diag.clinicToken }}
        - name: CLINIC_ENDPOINT
          value: {{ .Values.diag.clinicEndpoint | default "https://clinic.pingcap.com.cn" }}
      volumes:
      - name: pingcap-clinic-cert
        secret:
          secretName: {{ .Values.diag.secretName | default "pingcap-clinic-cert" }}
      {{- if .Values.diag.volume }}
      - name: diag-storage
{{ toYaml .Values.diag.volume | indent 8 }}
      {{- end }}