kind: ServiceAccount
apiVersion: v1
metadata:
  name: pingcap-clinic
  namespace: diag
  labels:
    app: pingcap-clinic
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pingcap-clinic
  namespace: diag
  labels:
    app: pingcap-clinic
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["pingcap.com"]
    resources: ["tidbclusters", "tidbmonitors"]
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: diag
  namespace: diag
subjects:
- kind: ServiceAccount
  name: pingcap-clinic
  namespace: diag
roleRef:
  kind: Role
  name: pingcap-clinic
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pingcap-clinic
  namespace: diag
  labels:
    app: pingcap-clinic
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["pingcap.com"]
    resources: ["tidbclusters", "tidbmonitors"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: diag
  namespace: diag
subjects:
- kind: ServiceAccount
  name: pingcap-clinic
  namespace: diag
roleRef:
  kind: ClusterRole
  name: pingcap-clinic
  apiGroup: rbac.authorization.k8s.io

